#####Producer Application######

######logger file#######
logging:
  file:
    name: ./logs/DigtDepartmentService.log
  #####logger patterns console,file##########
  pattern:
    console: '"%d{yyyy-MM-dd HH:mm:ss} - %msg%n"'
    file: '"%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"'
#####Tomcat server port###########   
server:
  port: 9091
######application name(URL)###########
spring:
  application:
    name: DIGT-DEPARTMENT-SERVICE
  boot:
    admin:
      client:
        url:
        - http://localhost:9095
        username: siva
        password: vdsi@123
  #####Database Properties##############
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    platform: mysql
    url: jdbc:mysql://localhost:3306/verizondigtdb
    username: root
  ######Springboot Data JPA Properties########
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  #####Zipkin URL (To find Service logger status and API Info)######
  zipkin:
    base-url: http://127.0.0.1:9411/

